language: python

python:
- '3.5'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

install:
  - pip install -r tests/requirements.txt
  - pip install .
before_script: flake8
script: tox

notifications:
  email:
  - sharpbit3618@gmail.com